/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.control.Conexao;
import fatec.poo.control.DaoPedido;
import fatec.poo.control.DaoProduto;
import fatec.poo.control.DaoVendedor;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import fatec.poo.control.DaoCliente;
import fatec.poo.control.DaoItemPedido;
import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import java.sql.Date;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fellipe
 */
public class GUIEmitirPedido extends javax.swing.JFrame {
    
    DefaultTableModel modTblItemPedido;
    public GUIEmitirPedido() {
        initComponents();
        modTblItemPedido = (DefaultTableModel)tblItemPedido.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    private Conexao conexao=null;
    
    private DaoPedido daoPedido=null;
    private Pedido pedido=null;
    
    private DaoVendedor daoVendedor=null;
    private Vendedor vendedor=null;
    
    private DaoProduto daoProduto=null;
    private Produto produto=null;
    
    private DaoCliente daoCliente=null;
    private Cliente cliente=null;
    
    private DaoItemPedido daoItemPedido=null;
    private ItemPedido itemPedido=null;
    
    int sequencia;
    boolean alterando;
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgrFormaPgto = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnConsultarPedido = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDataEmissao = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        rdbVista = new javax.swing.JRadioButton();
        rdbPrazo = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCpfCli = new javax.swing.JFormattedTextField();
        btnConsultarCli = new javax.swing.JButton();
        txtNomeCli = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtCpfVend = new javax.swing.JFormattedTextField();
        btnConsultarVend = new javax.swing.JButton();
        txtNomeVend = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnConsultarProd = new javax.swing.JButton();
        txtQtdeVendida = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        btnAddItem = new javax.swing.JButton();
        btnRmvItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItemPedido = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtValorTotPedido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtQtdeItemPedido = new javax.swing.JTextField();
        btnIncluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Número do Pedido");

        btnConsultarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPedidoActionPerformed(evt);
            }
        });

        jLabel2.setText("Data do Pedido");

        try {
            txtDataEmissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataEmissao.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento"));

        btgrFormaPgto.add(rdbVista);
        rdbVista.setSelected(true);
        rdbVista.setText("A Vista");

        btgrFormaPgto.add(rdbPrazo);
        rdbPrazo.setText("A Prazo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbVista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(rdbPrazo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbVista)
                    .addComponent(rdbPrazo))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarPedido)
                .addGap(58, 58, 58)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsultarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDataEmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        jLabel3.setText("CPF Cliente");

        try {
            txtCpfCli.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfCli.setEnabled(false);

        btnConsultarCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarCli.setEnabled(false);
        btnConsultarCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCliActionPerformed(evt);
            }
        });

        txtNomeCli.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarCli)
                .addGap(18, 18, 18)
                .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarCli, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtCpfCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        jLabel4.setText("CPF Vendedor");

        try {
            txtCpfVend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpfVend.setEnabled(false);

        btnConsultarVend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarVend.setEnabled(false);
        btnConsultarVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendActionPerformed(evt);
            }
        });

        txtNomeVend.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCpfVend, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarVend)
                .addGap(18, 18, 18)
                .addComponent(txtNomeVend)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarVend, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtCpfVend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        jLabel5.setText("Código do Produto");

        txtCodigo.setEnabled(false);

        btnConsultarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/pesq.png"))); // NOI18N
        btnConsultarProd.setEnabled(false);
        btnConsultarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarProdActionPerformed(evt);
            }
        });

        txtQtdeVendida.setText("0");
        txtQtdeVendida.setEnabled(false);

        jLabel6.setText("Qtde. Vendida");

        txtDescricao.setEnabled(false);

        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/add.png"))); // NOI18N
        btnAddItem.setText("Adicionar Item");
        btnAddItem.setEnabled(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnRmvItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/rem.png"))); // NOI18N
        btnRmvItem.setText("Remover Item");
        btnRmvItem.setEnabled(false);
        btnRmvItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvItemActionPerformed(evt);
            }
        });

        tblItemPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Prec. Unit.", "Qtde. Vend.", "Sub-Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItemPedido.setEnabled(false);
        jScrollPane1.setViewportView(tblItemPedido);

        jLabel7.setText("Valor Total do Pedido ");

        txtValorTotPedido.setText("0.00");
        txtValorTotPedido.setEnabled(false);

        jLabel8.setText("Quantidade de Itens do Pedido");

        txtQtdeItemPedido.setText("0");
        txtQtdeItemPedido.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(btnAddItem)
                                .addGap(18, 18, 18)
                                .addComponent(btnRmvItem)
                                .addGap(109, 109, 109))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtValorTotPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtQtdeItemPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConsultarProd)
                                .addGap(18, 18, 18)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtQtdeVendida)))
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtQtdeVendida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddItem)
                    .addComponent(btnRmvItem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtValorTotPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQtdeItemPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(277, 277, 277))
        );

        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/save.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIncluir)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnSair)
                .addGap(48, 48, 48))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnIncluir, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addGap(20, 20, 20))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlterar, btnExcluir, btnIncluir, btnSair});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPedidoActionPerformed
        try {
                Integer.parseInt(txtNumero.getText());
                
            } catch(NumberFormatException ex) {
                txtNumero.setText("");
                txtNumero.requestFocus();
                JOptionPane.showMessageDialog(null, "Insira apenas números!","Atenção", JOptionPane.WARNING_MESSAGE);
                return;
        }

        pedido = null;
        pedido = daoPedido.consultar(txtNumero.getText());
        
        if (pedido == null){
           txtNumero.setEnabled(false);
           btnConsultarPedido.setEnabled(false);
           txtDataEmissao.setEnabled(true);
           txtCpfCli.setEnabled(true);
           btnConsultarCli.setEnabled(true);
           txtDataEmissao.requestFocus();
           alterando = false;
       }
        else {
            txtNumero.setEnabled(false);
            btnConsultarPedido.setEnabled(false);
            txtDataEmissao.setText(pedido.getDataEmissao());
            if(pedido.isFormaPagto()) {
                rdbPrazo.setSelected(true);
            }
            rdbPrazo.setEnabled(false);
            rdbVista.setEnabled(false);
            txtCpfCli.setText(pedido.getCliente().getCpf());
            txtNomeCli.setText(pedido.getCliente().getNome());
            txtNomeVend.setText(pedido.getVendedor().getNome());
            txtCpfVend.setText(pedido.getVendedor().getCpf());
            
            txtCodigo.setEnabled(true);
            btnConsultarProd.setEnabled(true);
            txtQtdeVendida.setEnabled(true);
            btnRmvItem.setEnabled(true);
            
            btnIncluir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);
            tblItemPedido.setEnabled(true);
            
            cliente = pedido.getCliente();
            vendedor = pedido.getVendedor();
            
            itemPedido = daoItemPedido.consultar(pedido.getNumero());
            
            for(int i=0; i < itemPedido.getPedido().getItensPedido().size() ; i++) {
                
                String Linha[]= { itemPedido.getPedido().getItensPedido().get(i).getProduto().getCodigo(),
                                itemPedido.getPedido().getItensPedido().get(i).getProduto().getDescricao(),
                                Double.toString(itemPedido.getPedido().getItensPedido().get(i).getProduto().getPreco()),
                                Double.toString(itemPedido.getPedido().getItensPedido().get(i).getQtdeVendida()),
                                Double.toString(itemPedido.getPedido().getItensPedido().get(i).getQtdeVendida() * itemPedido.getPedido().getItensPedido().get(i).getProduto().getPreco())
                };
                
                produto = daoProduto.consultar(itemPedido.getProduto().getCodigo());
                pedido.setItensPedido(itemPedido.getPedido().getItensPedido());
                modTblItemPedido.addRow(Linha);
                alterando = true;
                AtualizaValoresPedido();
            }
            
       }
    }//GEN-LAST:event_btnConsultarPedidoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        conexao = new Conexao("BD1721024","BD1721024");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@apolo:1521:xe");
        daoPedido = new DaoPedido(conexao.conectar());
        daoCliente = new DaoCliente(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        daoProduto = new DaoProduto(conexao.conectar());
        daoItemPedido = new DaoItemPedido(conexao.conectar());
        
        /*
        conexao = new Conexao("SYSTEM","Fe78951230");
        conexao.setDriver("oracle.jdbc.driver.OracleDriver");
        conexao.setConnectionString("jdbc:oracle:thin:@localhost:1521:xe");
        daoProduto = new DaoProduto(conexao.conectar());
        daoPedido = new DaoPedido(conexao.conectar());
        daoCliente = new DaoCliente(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        daoItemPedido = new DaoItemPedido(conexao.conectar());
        */
        
        //*******************BLOCO PARA CONECTAR COM O MYSQL
        /*conexao = new Conexao("root","");
        conexao.setDriver("com.mysql.jdbc.Driver");
        conexao.setConnectionString("jdbc:mysql://localhost/bd_poo");
        daoProduto = new DaoProduto(conexao.conectar());
        daoPedido = new DaoPedido(conexao.conectar());
        daoCliente = new DaoCliente(conexao.conectar());
        daoVendedor = new DaoVendedor(conexao.conectar());
        daoItemPedido = new DaoItemPedido(conexao.conectar());*/
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        conexao.fecharConexao();
        dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnConsultarCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCliActionPerformed
        
        DateFormat df = new SimpleDateFormat ("dd/MM/yyyy");
        df.setLenient (false); // aqui o pulo do gato
        try {
            df.parse(txtDataEmissao.getText());
        } catch (ParseException ex) {
           JOptionPane.showMessageDialog(null, "Data do pedido inválida", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
        
        String cpf = txtCpfCli.getText().replaceAll("[.-]", "");
        if(Pessoa.validarCpf(cpf) == false){
            JOptionPane.showMessageDialog(null, "CPF Inválido!","Erro", JOptionPane.WARNING_MESSAGE);
            txtCpfCli.requestFocus();
        }
        else {
            cliente = null;
            cliente = daoCliente.consultar(txtCpfCli.getText().replaceAll("[.-]", ""));

            if (cliente == null) {
                JOptionPane.showMessageDialog(null, "Cliente não encontrado", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else {
                txtDataEmissao.setEnabled(false);
                txtNomeCli.setText(cliente.getNome());
                txtCpfCli.setEnabled(false);
                btnConsultarCli.setEnabled(false);
            
                txtCpfVend.setEnabled(true);
                btnConsultarVend.setEnabled(true);
                txtCpfVend.requestFocus();
                
                pedido = new Pedido(txtNumero.getText(), txtDataEmissao.getText());
                pedido.setCliente(cliente);
                
                if(rdbPrazo.isSelected()) { //Definindo se é pagamento a vista ou a prazo
                pedido.setFormaPagto(true);
                } else {
                    pedido.setFormaPagto(false);
                }
                
                rdbVista.setEnabled(false);               
                rdbPrazo.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnConsultarCliActionPerformed

    private void btnConsultarVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendActionPerformed
        String cpf = txtCpfVend.getText().replaceAll("[.-]", "");
        if(Pessoa.validarCpf(cpf) == false){
            JOptionPane.showMessageDialog(null, "CPF Inválido!","Atenção", JOptionPane.WARNING_MESSAGE);
            txtCpfVend.requestFocus();
        }
        else {
            vendedor = null;
            vendedor = daoVendedor.consultar(txtCpfVend.getText().replaceAll("[.-]", ""));

            if (vendedor == null) {
                JOptionPane.showMessageDialog(null, "Vendedor não encontrado", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else {
                txtNomeVend.setText(vendedor.getNome());
                txtCpfVend.setEnabled(false);
                txtCodigo.setEnabled(true);
                btnConsultarProd.setEnabled(true);
                txtCodigo.requestFocus();
                btnConsultarVend.setEnabled(false);
                
                pedido.setVendedor(vendedor);
            }
        }
    }//GEN-LAST:event_btnConsultarVendActionPerformed

    private void btnConsultarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProdActionPerformed
            try {
                Integer.parseInt(txtCodigo.getText());
                
            } catch(NumberFormatException ex) {
                txtCodigo.setText("");
                txtCodigo.requestFocus();
                JOptionPane.showMessageDialog(null, "Insira apenas números!","Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            produto = null;
            produto = daoProduto.consultar(txtCodigo.getText());
   
            if (produto == null) {
                JOptionPane.showMessageDialog(null, "Produto não encontrado", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else {
                
                int posLinha = VerificaLinha(Integer.parseInt(txtCodigo.getText()));
                if(posLinha >= 0) { //Cai aqui quando um produto já está nas linha
                    JOptionPane.showMessageDialog(null, "O produto já foi adicionado.","Atenção", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            
                txtDescricao.setText(produto.getDescricao());
                txtCodigo.setEnabled(false);
                btnAddItem.setEnabled(true);
                btnRmvItem.setEnabled(true);
                txtQtdeVendida.setEnabled(true);
                txtQtdeVendida.requestFocus();
                tblItemPedido.setEnabled(true);
                btnConsultarProd.setEnabled(false);
            }
    }//GEN-LAST:event_btnConsultarProdActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        try {
                Double.parseDouble(txtQtdeVendida.getText());
                
            } catch(NumberFormatException ex) {
                txtQtdeVendida.setText("");
                txtQtdeVendida.requestFocus();
                JOptionPane.showMessageDialog(null, "Insira apenas números!","Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
        
        if(Integer.parseInt(txtQtdeVendida.getText()) <= 0) {
            JOptionPane.showMessageDialog(null, "A quantidade a ser vendida deve ser maior que 0.","Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }  
        
            produto = null;
            produto = daoProduto.consultar(txtCodigo.getText());
                 
            if(cliente.getLimiteDisp() < (produto.getPreco() * Double.parseDouble(txtQtdeVendida.getText()))) {
                JOptionPane.showMessageDialog(null, "O saldo disponível do cliente não é o suficiente para essa compra.\n"
                                                    + "Saldo disponível: " + cliente.getLimiteDisp(),"Atenção", JOptionPane.WARNING_MESSAGE);
                txtCodigo.setEnabled(true);
                txtCodigo.setText("");
                txtDescricao.setText("");
                txtQtdeVendida.setText("");
                txtCodigo.requestFocus();
                btnConsultarProd.setEnabled(true);
                btnAddItem.setEnabled(false);
                
                return;
            }
            if(Double.parseDouble(txtQtdeVendida.getText()) > produto.getQtdeEstoque()) {
                JOptionPane.showMessageDialog(null, "A quantidade solicitada é maior do que a disponível em estoque.","Atenção", JOptionPane.WARNING_MESSAGE);
            }
            else {

                DecimalFormat df = new DecimalFormat("#0.00");

                double subtotal = produto.getPreco() * Double.parseDouble(txtQtdeVendida.getText());

                String Linha[]= { produto.getCodigo(),
                                    produto.getDescricao(),
                                    Double.toString(produto.getPreco()),
                                    txtQtdeVendida.getText(),
                                    Double.toString(subtotal)
                };

                modTblItemPedido.addRow(Linha);
                produto.setQtdeEstoque(produto.getQtdeEstoque() - Double.parseDouble(txtQtdeVendida.getText()));   

                int sequencia = 1;
                if(pedido.getItensPedido().size() > 0) {
                    sequencia = pedido.getItensPedido().get(pedido.getItensPedido().size()-1).getSequencia() + 1; //Sequencia será +1 da sequencia do ultimo item da ArrayList
                }

                itemPedido = null;
                itemPedido = new ItemPedido(sequencia, Double.parseDouble(txtQtdeVendida.getText()), produto);

                pedido.addItemPedido(itemPedido);

                txtCodigo.setEnabled(true);
                txtCodigo.setText("");
                txtCodigo.requestFocus();
                btnConsultarProd.setEnabled(true);
                txtDescricao.setText("");
                txtQtdeVendida.setText("0");
                btnAddItem.setEnabled(false);
                if(alterando == false) {
                    btnIncluir.setEnabled(true);
                }
                AtualizaValoresPedido();
        }
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnRmvItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvItemActionPerformed
        if(tblItemPedido.getSelectedRow() == -1) {
          JOptionPane.showMessageDialog(null, "Selecione uma linha para remover.", "Atenção", JOptionPane.ERROR_MESSAGE);
      }
      else {
            
            double valorTotal = Double.valueOf(tblItemPedido.getValueAt(tblItemPedido.getSelectedRow(), 4).toString());
            pedido.removerItemPedido(tblItemPedido.getSelectedRow(), valorTotal);
            modTblItemPedido.removeRow(tblItemPedido.getSelectedRow());
            AtualizaValoresPedido();
          
      }
    }//GEN-LAST:event_btnRmvItemActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        
        pedido.setDataPagto(pedido.getDataEmissao());        
        pedido.setSituacao(true);
        
        daoPedido.inserir(pedido);
        
        for(int x=0; x < pedido.getItensPedido().size();x++) {               
            daoItemPedido.inserir(pedido.getItensPedido().get(x));
            
            produto = daoProduto.consultar(pedido.getItensPedido().get(x).getProduto().getCodigo());
            produto.setQtdeEstoque(produto.getQtdeEstoque() - pedido.getItensPedido().get(x).getQtdeVendida()); //Tirando a quantidade do estoque
            daoProduto.alterar(produto);
        }
        
        if(pedido.isFormaPagto()) {
            daoCliente.alterar(cliente); //Atualizando para alterar o limite disponivel
        }
        JOptionPane.showMessageDialog(null, "Pedido efetuado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Confirma a alteração?", "Alteração", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            
            daoItemPedido.excluir(itemPedido); //Removendo todos os itens
            
            for(int x=0; x < pedido.getItensPedido().size();x++) { //Inserindo os novos itens         
             daoItemPedido.inserir(pedido.getItensPedido().get(x));

             produto = daoProduto.consultar(pedido.getItensPedido().get(x).getProduto().getCodigo());
             produto.setQtdeEstoque(produto.getQtdeEstoque() - pedido.getItensPedido().get(x).getQtdeVendida()); //Tirando a quantidade do estoque
             daoProduto.alterar(produto);
         }
            if(pedido.isFormaPagto()) {
            daoCliente.alterar(cliente); //Atualizando para alterar o limite disponivel
        }
        JOptionPane.showMessageDialog(null, "Pedido alterado com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Confirma a exclusão?", "Exclusão", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == 0) {
            daoPedido.excluir(pedido);
            daoItemPedido.excluir(itemPedido);
            JOptionPane.showMessageDialog(null, "Pedido excluído com sucesso.", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void AtualizaValoresPedido() {
        
            double valorTotalPedido = 0;
            int quantidadeItensPedido = 0;
            for(int i=0;i<modTblItemPedido.getRowCount();i++) {
                 valorTotalPedido += Double.parseDouble(String.valueOf(modTblItemPedido.getValueAt(i, 4)));
            }
            txtValorTotPedido.setText(Double.toString(valorTotalPedido));

            for(int i=0;i<modTblItemPedido.getRowCount();i++) {
                 quantidadeItensPedido += Double.parseDouble(String.valueOf(modTblItemPedido.getValueAt(i, 3)));
            }
            txtQtdeItemPedido.setText(Integer.toString(quantidadeItensPedido));
    }
    
    private int VerificaLinha(int codigo) {

        for(int i=0;i<modTblItemPedido.getRowCount();i++) {
            if(codigo == Integer.parseInt(String.valueOf(modTblItemPedido.getValueAt(i, 0)))) {
                return i;
            }
        }
        return -1;
    }
    
    private void ReiniciarForm () {
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEmitirPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEmitirPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgrFormaPgto;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultarCli;
    private javax.swing.JButton btnConsultarPedido;
    private javax.swing.JButton btnConsultarProd;
    private javax.swing.JButton btnConsultarVend;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnRmvItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdbPrazo;
    private javax.swing.JRadioButton rdbVista;
    private javax.swing.JTable tblItemPedido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtCpfCli;
    private javax.swing.JFormattedTextField txtCpfVend;
    private javax.swing.JFormattedTextField txtDataEmissao;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtNomeCli;
    private javax.swing.JTextField txtNomeVend;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtQtdeItemPedido;
    private javax.swing.JTextField txtQtdeVendida;
    private javax.swing.JTextField txtValorTotPedido;
    // End of variables declaration//GEN-END:variables
}
